version = 1

[merge]
method = "squash"
notify_on_conflict = false
delete_branch_on_merge = true
prioritize_ready_to_merge = true
automerge_label = "dependencies"

[approve]
auto_approve_usernames = ["dependabot"]