name: "Update dependencies"
on:
  schedule:
    - cron: "0 9 1-7 * 2"

jobs:
  Dependencies:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Install dependencies and upgrade
        run: |
          yarn
          npx yarn-upgrade-all

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          labels: dependencies
          delete-branch: true
          title: "${{ steps.date.outputs.date }} - Monthly Deps upgrade"
          commit-message: "chore(deps): Update dependencies"
          branch: "dependencies/${{ steps.date.outputs.date }}"
